// <auto-generated />
using System;
using Library.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InlämningDatabas.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20210126174439_v5")]
    partial class v5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Library.Models.Date", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateOfTemperature")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Date");
                });

            modelBuilder.Entity("Library.Models.Temperature", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("DateID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfTemperatureReading")
                        .HasColumnType("datetime2");

                    b.Property<int>("Humidity")
                        .HasColumnType("int");

                    b.Property<string>("PositionForReading")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TemperatureReading")
                        .HasColumnType("real");

                    b.Property<DateTime>("TimeOfTemperatureReading")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("DateID");

                    b.ToTable("Temperature");
                });

            modelBuilder.Entity("Library.Models.Temperature", b =>
                {
                    b.HasOne("Library.Models.Date", null)
                        .WithMany("Temperatures")
                        .HasForeignKey("DateID");
                });

            modelBuilder.Entity("Library.Models.Date", b =>
                {
                    b.Navigation("Temperatures");
                });
#pragma warning restore 612, 618
        }
    }
}
